use FIFO for boosting (v2)
bristot/stalld pull request #19
Opened 2020-09-17 02:21 UTC by clrkwllms

This is a set of changes that allow stalld to operation without the
Deadline scheduler policy. The idea is to emulate how deadline
works boosting a starving thread. When a boost operation is called
for, the fifo boosting logic figures out how many 'periods' would
be in the specified boost duration (default 3 seconds) and iterates
for that number of periods, boosting the starving thread to fifo:98,
sleeping for the 'runtime', deboosting to the original policy, sleeping
for the remainder (period - runtime) and repeating until the boost
duration is done.

The FIFO boost logic is turned on when the running kernel does not
support DEADLINE or when the command line option -F/--force_fifo is
specified.

Signed-off-by: Clark Williams <clark.williams@gmail.com>

2020-09-17 06:53 UTC, jlelli requested changes

2020-09-17 06:53 UTC, jlelli commented on src/stalld.c
> +	attr.sched_policy   = SCHED_DEADLINE;
Isn't this SCHED_FIFO? :-)

2020-09-17 06:53 UTC, jlelli commented on src/stalld.c
> +	remainder_ts.tv_nsec = config_dl_period - config_dl_runtime;
I fear we can accumulate rounding/timers errors this way (like if we run or sleep for more/less than required).
Think we need to always increment the timer we use for sleeping until next period of config_dl_period, no matter what runtime_ts has been.
So read clock before entering the loop and than add config_dl_period to it at each iteration and sleep until that instant of time.

2020-09-17 06:53 UTC, jlelli commented on src/stalld.c
> +		ts = remainder_ts;
In any case this has to be updated at each round, no?

2020-09-17 06:53 UTC, jlelli commented on src/stalld.c
> +	ret = boost_with_deadline(0) == 0 ? 1 : 0;
We probably need to use "safer" DEADLINE parameters for this check or it might take a long time (seconds) to just know if we can use DEADLINE (current thread will be throttled after, say, 20us and has to wait 1s to execute for another 20us, etc).

2020-09-17 06:53 UTC, jlelli commented on src/stalld.c
> +	restore_policy(0, &attr);
This can fail as well. We probably need to check for return value.

2020-09-17 11:47 UTC, clrkwllms commented on src/stalld.c
> +	ret = boost_with_deadline(0) == 0 ? 1 : 0;
You think we should use runtime == period or at least some majority percentage so that we'll change, continue running and change back relatively quickly?

2020-09-17 11:48 UTC, clrkwllms commented on src/stalld.c
> +	restore_policy(0, &attr);
yeah, I missed checking that. Question with a lot of these is whether we should just quit or try to continue running?

2020-09-17 11:51 UTC, bristot commented on src/stalld.c
> +	ret = boost_with_deadline(0) == 0 ? 1 : 0;
runtime= period might not work on single-core, maybe period/2?

2020-09-17 11:52 UTC, clrkwllms commented on src/stalld.c
> +	remainder_ts.tv_nsec = config_dl_period - config_dl_runtime;
yes, I thought of that, but then thought "so what?". We're not trying to meet a realtime deadine here, we're just trying to provide a timeslice to a stalled thread.If something delays us a bit, no big thing. I can resync the clock within the loop but not sure it's worth the additional code.

2020-09-17 11:52 UTC, bristot commented on src/stalld.c
> +	return ret;
We can also fail to set FIFO, if the user is non-root for example. If we fail FIFO, we can fallback to log_only.

2020-09-17 11:52 UTC, clrkwllms commented on src/stalld.c
> +	attr.sched_policy   = SCHED_DEADLINE;
wups...

2020-09-17 11:56 UTC, jlelli commented on src/stalld.c
> +	restore_policy(0, &attr);
Failing to restore policy is pretty bad.. it shouldn't happen in the normal case.
So if we fail it means that stalled task could potentially continue running with RT/DEADLINE priority potentially causing spikes etc. We should probably report that (syslog)? Then maybe continue as it might be a correctable error?

2020-09-17 14:37 UTC, clrkwllms commented on src/stalld.c
> +		ts = remainder_ts;
Ok, after an IRC conversation, are we agreed that it's ok to have some drift right now? If we find that we're seeing issues due to doing relative sleeps and not sync'ing with the clock in the boost loop, we can fix it later?

2020-09-17 14:52 UTC, jlelli commented on src/stalld.c
> +		ts = remainder_ts;
Yep. Works for me.

2020-09-17 15:21 UTC, clrkwllms commented on src/stalld.c
> +	ret = boost_with_deadline(0) == 0 ? 1 : 0;
How about runtime = (period/2)?

2020-09-17 15:21 UTC, clrkwllms commented on src/stalld.c
> +	restore_policy(0, &attr);
Ok, I''l add an if to check the return and log a message on failure

2020-09-17 15:23 UTC, clrkwllms commented on src/stalld.c
> +	return ret;
Ah, should I modify check_for_deadline() to be something line check_policies() and try to set deadline as well? Both fail I can modify the logic to be log only at that point?

2020-09-17 15:23 UTC, clrkwllms commented on src/stalld.c
> +	attr.sched_policy   = SCHED_DEADLINE;
BTW, this change means there will be a v3 forthcoming...

2020-09-17 22:13 UTC, clrkwllms commented on src/stalld.c
> +	ret = boost_with_deadline(0) == 0 ? 1 : 0;
Went with runtime being half of period

2020-09-18 12:52 UTC, jlelli reviewed
@clrkwllms, was adding a commit on top of v2 intentional?
Usually one needs to force push to the same branch to update a pull request.

2020-09-18 12:52 UTC, jlelli commented on src/stalld.c
> +	if (ret < 0) {
Ideally I think we should still check for ENOSYS, because, even if unlikely, it might just be that other DEADLINE tasks are already on the system and 50% of bandwidth is too much (but DEADLINE is usable).

2020-09-18 13:12 UTC, clrkwllms commented on src/stalld.c
> +	if (ret < 0) {
> @clrkwllms, was adding a commit on top of v2 intentional?
> Usually one needs to force push to the same branch to update a pull request.
I was trying to update, mainly to fix the cut-n-paste error where we used DEADLINE in the fifo boost routine. I'll admit to being hazy on the procedures for adding a commit to a pull request.

2020-09-18 13:15 UTC, clrkwllms commented on src/stalld.c
> +	if (ret < 0) {
Regarding the check for ENOSYS, that just tells me that DEADLINE is not supported, correct? What should we do if we get something *other* than ENOSYS? Quit?

2020-09-18 13:19 UTC, jlelli commented on src/stalld.c
> +	if (ret < 0) {
I'd say something other than ENOSYS is actually good. It means that we can use DEADLINE. Since stalld uses a very small bandwidth, most likely it will be able to work correctly (if it doesn't we can quit later I think).
Maybe question is, what we want to do if setting to DEADLINE fails later on for a stalled task? Quit or still fall back to FIFO?

2020-09-18 13:41 UTC, clrkwllms commented on src/stalld.c
> +	if (ret < 0) {
Ok, maybe period / 4 is a good number for the test and if we see an error !ENOSYS then we can presume that we have the deadline scheduler. Other error we may want to deal with is permissions. Maybe we should make a root check at the start of main and just exit if we're not running as root?  Then if we get into check_policies() and get an error we can just log the error and switch over to logging only?

2020-09-18 13:43 UTC, jlelli commented on src/stalld.c
> +	if (ret < 0) {
Yeah, makes sense to me.

2020-09-23 23:37 UTC, closed without merging